// components/styles/SubCategoryListStyles.js
import { StyleSheet,Platform } from "react-native";
import { COLORS } from "../../../../../Redux/constants/theme";

export default StyleSheet.create({
  container: {
    marginVertical: 6,
    paddingHorizontal: 5,
    gap: 10,
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingTop: 10,
  },
  card: {
    flex: 1,
    marginHorizontal: 7,
    marginBottom: 14,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F3F4F6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  imageWrapper: {
    width: "100%",
    height: 110,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  content: {
    padding: 16,
    minHeight: 25,
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    width: "100%",
  },
  title: {
    fontSize: 14,
    fontWeight: "800",
    color: "#1F2937",
    marginBottom: 8,
    lineHeight: 15,
    textAlign: "center",
   fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'Roboto'
  },
  browseBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.services,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    minHeight: 36,
  },
  browseText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#FFFFFF",
    flex: 1,
  },
  cashbackTag: {
    position: "absolute",
    top: 6,
    right: 6,
    backgroundColor: "#FF3B30",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 16,
    elevation: 8,
    shadowColor: "#FF3B30",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 50,
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  cashbackText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.5,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  cashbackSubText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "600",
  },
});
